services:
  - type: web
    name: mark-portfolio
    env: php
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y nodejs npm
      composer install --no-dev --optimize-autoloader
      cp .env.example .env || true
      php artisan key:generate
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mark-portfolio.onrender.com
      - key: PORT
        value: 10000
