services:
  - type: web
    name: laravel-react-portfolio
    env: php
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://laravel-react-portfolio.onrender.com
